# Generated by Django 4.0.4 on 2024-04-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=45)),
                ('spa_word', models.CharField(max_length=45)),
                ('grammar_type', models.CharField(max_length=45)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
