# Generated by Django 4.0.4 on 2024-04-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studypath', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='grammartype',
            new_name='grammar_type',
        ),
    ]
