# Generated by Django 4.0.4 on 2024-04-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studypath', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
