# Generated by Django 4.0.4 on 2024-04-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypath', '0002_rename_grammartype_word_grammar_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
