# Generated by Django 4.0.4 on 2024-04-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypath', '0003_word_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='gender',
        ),
        migrations.AddField(
            model_name='word',
            name='spa_word_fem',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
