# Generated by Django 4.0.4 on 2024-04-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studypath', '0004_remove_word_gender_word_spa_word_fem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='spa_word_fem',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
