# Generated by Django 4.0.4 on 2024-04-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studypath', '0005_alter_word_spa_word_fem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammartype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='grammartype',
            table='studypath_grammartype',
        ),
        migrations.AlterModelTable(
            name='word',
            table='studypath_word',
        ),
    ]
