# Generated by Django 4.0.4 on 2024-04-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studypath', '0007_stage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='spa_word',
            new_name='fre_word',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='spa_word_fem',
            new_name='fre_word_fem',
        ),
    ]
