# Generated by Django 4.0.4 on 2024-04-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studypath', '0008_rename_spa_word_word_fre_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('description', models.CharField(max_length=45)),
                ('grammar_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studypath.grammartype')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studypath.stage')),
            ],
            options={
                'db_table': 'studypath_step',
                'managed': True,
            },
        ),
    ]
