# Generated by Django 4.0.4 on 2024-05-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studypath', '0009_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartype',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studypath.stage'),
            preserve_default=False,
        ),
    ]
